### ISSUE TITLE
license

### ISSUE THREAD

**Issue by iqualfragile** [veer66/kyotocabinet-rs#1]
you gave the license as lgpl.
the native lib you are linking to, kyotocabinet is licensed as gpl, unlike its predecessor tokyocabinet.
they do include a linking exception for some open source licensed products. it would be nice to see a mention/discussion of that circumstance in the readme.

**Comment by veer66** [comment]
Thank you for informing me I will change it to GPL.

**Comment by veer66** [comment]
It is in GPL now https://github.com/veer66/kyotocabinet-rs/commit/58e3442a8e0e8560b22c3e0057a4866d3794f6e1.

Is it okay?

**Comment by iqualfragile** [comment]
not entirely, for one some other crates depend on yours, and at least one of them is mit-licensed.
also you might not need to actually change the license. have a look at http://fallabs.com/kyotocabinet/pkg/, download a package, and read through the gpl exceptions. the authors of kyotocabinet explicitly allowed exceptions for open source projects licensed under one of ~7 licenses.

**Comment by veer66** [comment]
How about the latest change?

**Comment by veer66** [comment]
If you prefer, you can give me a pull request.

**Comment by iqualfragile** [comment]
well, i myself am no lawyer, i just happened to see that both were licensed differently.
the problem i (still) have with the way it is now, is that if this is actually legal, any closed source project could just write a mit-wrapper around kyotocabinet, publish that and use it in their closed source project.
which i am not sure is what the authors intended, so i am a bit unsure if that works.
licenses are hard.

**Comment by veer66** [comment]
Thank you. For this project, I suppose that the exception is clear.
